# Generated by Django 4.1.3 on 2023-01-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_person_middle_name_alter_courseattendance_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='course_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_unit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.DeleteModel(
            name='RegisteredCourses',
        ),
    ]
