# Generated by Django 4.1.3 on 2023-01-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0005_rename_course_name_course_course_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Attendance.programme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseattendance',
            name='session',
            field=models.CharField(default='2022/2023', max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='session',
            field=models.CharField(default='2022/2023', max_length=10),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='students',
            field=models.ManyToManyField(to='Attendance.student'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='post',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='session',
            field=models.CharField(default='2022/2023', max_length=10),
        ),
    ]
