# Generated by Django 4.1.3 on 2023-02-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0007_remove_course_lecturer_remove_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
    ]
