# Generated by Django 4.1.3 on 2023-02-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0009_alter_staff_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='programme',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Attendance.department'),
            preserve_default=False,
        ),
    ]
