# Generated by Django 4.1.3 on 2023-02-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0013_course_lecturer_registeredstudent_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='others',
            field=models.ManyToManyField(to='Attendance.staff'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='Attendance.staff'),
        ),
    ]
