# Generated by Django 4.1.3 on 2023-02-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0014_course_others_alter_course_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Attendance.course'),
            preserve_default=False,
        ),
    ]
