# Generated by Django 4.1.3 on 2023-02-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0015_studentattendance_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseattendance',
            name='time',
            field=models.TimeField(default='20:19:01'),
            preserve_default=False,
        ),
    ]
