# Generated by Django 4.1.3 on 2023-03-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0016_courseattendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
