# Generated by Django 4.1.3 on 2023-03-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0018_remove_course_lecturer_remove_course_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseallocation',
            name='session',
            field=models.CharField(default='2022/2023', max_length=10),
        ),
        migrations.AlterField(
            model_name='courseattendance',
            name='session',
            field=models.CharField(default='2022/2023', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='session',
            field=models.CharField(default='2022/2023', max_length=10),
        ),
    ]
